name: Java with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # jar file build and permission
      - name: Grant
        run: chmod +x gradlew
      - name: Build Jar
        run: ./gradlew build bootJAR

      # runner(ubuntu) docker buildx install
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      # docker image build to push to docker hub